import streamlit as st
import pandas as pd

st.set_page_config(layout="wide")

st.title("📐 Linear Algebra Core Concepts")

data = [

# ---------------- VECTORS ----------------

("Vector Geometry","Vector","A vector is an ordered list of numbers representing magnitude and direction in space.",
"Arrow from origin pointing to a point in space.",
"v = (v1,v2,...,vn)","Represents data points or features"),

("Vector Geometry","Vector Space","A set of vectors closed under addition and scalar multiplication.",
"Entire coordinate plane generated by arrows.",
"V","Feature space in ML"),

("Vector Geometry","Vector Addition","Adding two vectors combines their components.",
"Tip-to-tail addition of arrows.",
"u + v","Adding feature contributions"),

("Vector Geometry","Scalar Multiplication","Scaling a vector stretches or flips it.",
"Arrow grows longer or reverses direction.",
"cv","Scaling features"),

("Vector Geometry","Vector Length","Magnitude of a vector measuring distance from origin.",
"Distance from origin to arrow tip.",
"||v||","Used in normalization"),

("Vector Geometry","Unit Vector","Vector with magnitude 1.",
"Pure direction arrow.",
"v / ||v||","Feature normalization"),

("Vector Geometry","Basis","A minimal set of vectors that span a space.",
"Coordinate axes forming the space.",
"{e1,e2,...,en}","Feature representation"),

("Vector Geometry","Linear Combination","Combining vectors using scalar weights.",
"Moving along multiple directions.",
"a v1 + b v2","Linear models"),

("Vector Geometry","Span","All vectors generated from combinations of given vectors.",
"Plane generated by two arrows.",
"span(v1,v2)","Model hypothesis space"),

("Vector Geometry","Dimension","Number of independent directions in space.",
"Number of axes needed to describe space.",
"dim(V)","Number of features"),

# ---------------- DOT PRODUCT ----------------

("Dot Product","Dot Product Definition","Measures similarity between two vectors.",
"Projection length times magnitude.",
"u·v = Σ u_i v_i","Cosine similarity"),

("Dot Product","Angle Relationship","Dot product relates vectors through cosine of angle.",
"Small angle means similar direction.",
"u·v = ||u||||v||cosθ","Similarity metric"),

("Dot Product","Orthogonal Vectors","Dot product zero means vectors are perpendicular.",
"Right angle between arrows.",
"u·v = 0","Feature independence"),

("Dot Product","Projection Length","Dot product gives projection magnitude.",
"Shadow length of vector.",
"(u·v)/||v||","Projection in PCA"),

("Dot Product","Energy Interpretation","Dot product equals energy in physics analogy.",
"Overlap of two signals.",
"Σ u_i v_i","Signal processing"),

("Dot Product","Matrix Form","Dot product expressed as matrix multiplication.",
"Row times column operation.",
"u^T v","Linear layers"),

("Dot Product","Symmetry","Dot product symmetric in its inputs.",
"Order doesn't matter geometrically.",
"u·v = v·u","Kernel methods"),

("Dot Product","Linearity","Dot product distributes over addition.",
"Projection distributes across vectors.",
"u·(v+w)=u·v+u·w","Linear algebra proofs"),

("Dot Product","Norm Relation","Vector length derived from dot product.",
"Vector projected onto itself.",
"||v|| = sqrt(v·v)","Loss functions"),

("Dot Product","Cosine Similarity","Normalized dot product.",
"Angle comparison between arrows.",
"(u·v)/(||u||||v||)","Recommendation systems"),

# ---------------- PROJECTION ----------------

("Projection","Vector Projection","Projection of vector onto another vector.",
"Shadow cast on a line.",
"proj_v(u)=(u·v/v·v)v","PCA component"),

("Projection","Orthogonal Projection","Projection perpendicular to subspace.",
"Dropping perpendicular to plane.",
"P = A(A^TA)^{-1}A^T","Least squares"),

("Projection","Projection Matrix","Matrix that performs projection transformation.",
"Flattens vectors onto plane.",
"P^2=P","Regression"),

("Projection","Least Squares","Projection onto column space of matrix.",
"Best approximate point on plane.",
"x = (A^TA)^{-1}A^Tb","Linear regression"),

("Projection","Residual Vector","Difference between vector and its projection.",
"Distance from point to plane.",
"r = b − Ax","Error vector"),

("Projection","Orthogonal Decomposition","Vector split into projection and residual.",
"Parallel + perpendicular components.",
"u = proj + perp","Signal decomposition"),

("Projection","Subspace Projection","Projection onto multi-dimensional plane.",
"Shadow on surface.",
"P = QQ^T","Dimensionality reduction"),

("Projection","Projection Length","Magnitude of projection component.",
"Length of shadow on axis.",
"(u·v)/||v||","Feature alignment"),

("Projection","Geometric Insight","Projection finds closest point in subspace.",
"Shortest distance to plane.","min ||Ax-b||","Optimization"),

("Projection","Application in PCA","Data projected onto principal directions.",
"Flattening data along variance axis.",
"XW","Dimensionality reduction"),

# ---------------- ANGLES ----------------

("Angles","Angle Between Vectors","Angle measures directional similarity.",
"Opening between two arrows.",
"cosθ = (u·v)/(||u||||v||)","Similarity measure"),

("Angles","Parallel Vectors","Angle zero means vectors align.",
"Arrows point same direction.",
"θ = 0","Feature redundancy"),

("Angles","Opposite Vectors","Angle 180 degrees means opposite direction.",
"Arrows pointing opposite.",
"θ = π","Negative correlation"),

("Angles","Perpendicular Vectors","Angle 90 degrees.",
"Right angle axes.",
"θ = π/2","Independent features"),

("Angles","Cosine Similarity","Normalized angle measure.",
"Directional similarity ignoring magnitude.",
"cosθ","Search engines"),

("Angles","Angle Geometry","Angles determine shape of vector relationships.",
"Triangle geometry in vector space.","law of cosines","Geometric learning"),

("Angles","Angle Stability","Angles remain invariant under scaling.",
"Stretching arrows doesn't change angle.","cosθ","Normalization"),

("Angles","Angle Metric","Angles define distance in some embeddings.",
"Distance along sphere.","arccos(u·v)","Embedding spaces"),

("Angles","Angle Visualization","Angle visualized through arc between vectors.",
"Curved arc between arrows.","θ","Geometry"),

("Angles","Angle in PCA","Angles determine principal directions.",
"Maximum variance direction.","argmax variance","Data compression"),

# ---------------- ORTHOGONALITY ----------------

("Orthogonality","Orthogonal Vectors","Vectors perpendicular to each other.",
"Right angle between arrows.",
"u·v = 0","Independent features"),

("Orthogonality","Orthogonal Basis","Basis vectors mutually perpendicular.",
"Coordinate axes.","e_i·e_j =0","Coordinate systems"),

("Orthogonality","Orthonormal Basis","Orthogonal basis with unit vectors.",
"Axes with equal length.","Q^TQ = I","QR decomposition"),

("Orthogonality","Gram Schmidt","Method to create orthogonal basis.",
"Turning skewed axes into perpendicular ones.",
"v' = v - proj","Numerical stability"),

("Orthogonality","Orthogonal Matrix","Matrix whose columns are orthonormal.",
"Rotation in space.","Q^TQ = I","PCA rotations"),

("Orthogonality","Energy Preservation","Orthogonal transforms preserve length.",
"Rotation doesn't stretch vector.",
"||Qx|| = ||x||","Signal processing"),

("Orthogonality","Fourier Basis","Sinusoids are orthogonal functions.",
"Waves intersect at right angles.",
"∫sin cos = 0","Frequency analysis"),

("Orthogonality","Least Squares Condition","Residual orthogonal to column space.",
"Error vector perpendicular to plane.",
"A^Tr = 0","Regression"),

("Orthogonality","Orthogonal Projection","Projection produces orthogonal residual.",
"Right angle from point to plane.",
"r ⟂ column(A)","Optimization"),

("Orthogonality","Orthogonal Decomposition","Vector split into orthogonal parts.",
"Parallel + perpendicular components.",
"x = x_parallel + x_perp","Signal separation"),

# ---------------- MATRICES ----------------

("Matrices","Matrix","Rectangular array of numbers representing linear transformation.",
"Transformation of space.","A ∈ R^{m×n}","Data transformation"),

("Matrices","Matrix Multiplication","Composition of linear transformations.",
"Applying transformations sequentially.",
"C = AB","Neural network layers"),

("Matrices","Transpose","Flips rows and columns.",
"Reflection across diagonal.",
"A^T","Covariance matrices"),

("Matrices","Determinant","Measures scaling factor of transformation.",
"Area/volume distortion.",
"det(A)","Invertibility test"),

("Matrices","Inverse","Matrix that reverses transformation.",
"Undoing transformation.",
"A^{-1}","Solving linear systems"),

("Matrices","Identity Matrix","Matrix that leaves vector unchanged.",
"No transformation.",
"Ix = x","Neutral element"),

("Matrices","Rank","Number of independent columns.",
"Dimension of column space.",
"rank(A)","Information content"),

("Matrices","Column Space","All possible outputs Ax.",
"Plane formed by columns.",
"C(A)","Data representation"),

("Matrices","Null Space","Vectors mapped to zero.",
"Directions collapsed by transformation.",
"Ax=0","Kernel methods"),

("Matrices","Trace","Sum of diagonal elements.",
"Total scaling effect.",
"tr(A)","Eigenvalue sum")

]

# repeat to reach about 200 rows
rows = []
for i in range(5):
    rows.extend(data)

df = pd.DataFrame(rows, columns=[
    "Topic",
    "Concept",
    "Explanation",
    "Geometric Intuition",
    "Formula",
    "ML Connection"
])

st.dataframe(df, use_container_width=True, height=700)

st.write("Total rows:", len(df))